### ISSUE TITLE
Rations disappearing when picked up with max inventory

### ISSUE THREAD

**Issue by caligari87** [caligari87/HDScav#4]
Reported by @beatcrazed via Discord

> Oh, and I've just found this: If you are at max rations and pick up another, the ration disappears into the ether

**Comment by caligari87** [comment]
opening so I don't forget to fix this later

>MatthewTheGlutton: spawn2
> not spawn
> never override spawn in hdpickup
> because of some code that cannot be done in either CreateTossable or PostBeginPlay

https://github.com/caligari87/HDScav/blob/712046975316907dcc0673b80a0323544eb48ce8/zscript.zsc#L186

**Comment by MatthewTheGlutton** [comment]
As of latest HD git spawn without spawn2 should work fine.

**Comment by caligari87** [comment]
Awesome. I actually committed a change to `spawn2` last night, should I revert it?

**Comment by MatthewTheGlutton** [comment]
Check to see if it works, and if so please do!

**Comment by MatthewTheGlutton** [comment]
I figured I'd missed something doing that conversion.

Will fix tonight.

**Comment by caligari87** [comment]
Looks like it works now, thank you!
